### ISSUE TITLE
Dot notation uncertainty

### ISSUE THREAD

**Issue by dy** [compute-io/incrdatespace#2]
I tried to cover incrdatespace duration parsing cases in https://github.com/jkroso/parse-duration/issues/7 and got a gotcha. We may want to indicate fraction of time as `.2s` for example, that is `0.2s`. But the dot notation used here considers it as a part of combined date `1d.4s`, which is `1day 4seconds`. What is the purpose/reason for the dot notation here? Wouldn't it be better to stick to standard svg-paths/floating numbers convention, so than `1d.4s` means `1day 0.4seconds`?

**Comment by kgryte** [comment]
`.2s` is equivalent to `200ms`. Not allowing fractional values was intentional, otherwise you allow things like `.000000000000000000000002ms`, which is not particularly informative. I would rather people be explicit in what they want by breaking an increment into its various parts.
